### PR TITLE
php 8.4 compatibility

### PR DESCRIPTION
**Pull request by Xon**
https://wiki.php.net/rfc/deprecate-implicitly-nullable-types

### CODE REVIEW

**Comment by JoshyPHP** [comment]
Oh that sucks, I'm going to have to change like 100K lines of code. Thanks for the heads up. :+1:

**Comment by JoshyPHP** [comment]
I didn't notice that was a PR, thought it was an issue. Realized when I went back to get the issue number. Anyway, thanks again.

**Comment by Xon** [comment]
@JoshyPHP I've been using this regex `function.*\([^\?\)]+\s*[\w]+\s*\$[\w]+\s*=\s*null.*?\)` to audit for this issue without needing an explicit php-cs-fixer thingy.

**Comment by JoshyPHP** [comment]
Sounds nice. I might use that in my editor or with `grep` to get a quick overview of which repos I need to update. I tried php-cs-fixer on a couple of projects and it was quick and painless.

**Pull request closed without merging**
